/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/oauth/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect */
        get: operations["connect_api_frameio_oauth_connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_frameio_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_frameio_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect */
        post: operations["disconnect_api_frameio_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_frameio_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_frameio_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_frameio_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Folders
         * @description Direct child folders of `folder_id` (pass a project's root_folder_id to start).
         */
        get: operations["list_folders_api_frameio_folders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frameio/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description Direct child files of `folder_id` (for download-link source selection).
         */
        get: operations["list_files_api_frameio_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Destinations */
        get: operations["list_destinations_api_destinations_get"];
        put?: never;
        /** Create Destination */
        post: operations["create_destination_api_destinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{dest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destination */
        get: operations["get_destination_api_destinations__dest_id__get"];
        put?: never;
        post?: never;
        /** Delete Destination */
        delete: operations["delete_destination_api_destinations__dest_id__delete"];
        options?: never;
        head?: never;
        /** Update Destination */
        patch: operations["update_destination_api_destinations__dest_id__patch"];
        trace?: never;
    };
    "/api/upload-links/extension-preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extension Preset */
        get: operations["extension_preset_api_upload_links_extension_preset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_api_upload_links_get"];
        put?: never;
        /** Create Link */
        post: operations["create_link_api_upload_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload-links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Link */
        get: operations["get_link_api_upload_links__link_id__get"];
        put?: never;
        post?: never;
        /** Delete Link */
        delete: operations["delete_link_api_upload_links__link_id__delete"];
        options?: never;
        head?: never;
        /** Update Link */
        patch: operations["update_link_api_upload_links__link_id__patch"];
        trace?: never;
    };
    "/api/upload-links/{link_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Link */
        post: operations["revoke_link_api_upload_links__link_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Link */
        get: operations["resolve_link_api_public_links__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Code */
        post: operations["request_code_api_public_links__token__request_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/verify-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Link Password */
        post: operations["verify_link_password_api_public_links__token__verify_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_public_links__token__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request File Upload */
        post: operations["request_file_upload_api_public_links__token__sessions__session_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/sessions/{session_id}/files/{file_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete File */
        post: operations["complete_file_api_public_links__token__sessions__session_id__files__file_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/links/{token}/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Session */
        post: operations["complete_session_api_public_links__token__sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_api_download_links_get"];
        put?: never;
        /** Create Link */
        post: operations["create_link_api_download_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download-links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Link */
        get: operations["get_link_api_download_links__link_id__get"];
        put?: never;
        post?: never;
        /** Delete Link */
        delete: operations["delete_link_api_download_links__link_id__delete"];
        options?: never;
        head?: never;
        /** Update Link */
        patch: operations["update_link_api_download_links__link_id__patch"];
        trace?: never;
    };
    "/api/download-links/{link_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Link */
        post: operations["revoke_link_api_download_links__link_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/downloads/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Link */
        get: operations["resolve_link_api_public_downloads__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/downloads/{token}/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Code */
        post: operations["request_code_api_public_downloads__token__request_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/downloads/{token}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_api_public_downloads__token__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/downloads/{token}/sessions/{session_id}/files/{file_id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Download Url */
        post: operations["get_download_url_api_public_downloads__token__sessions__session_id__files__file_id__url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email Status */
        get: operations["email_status_api_settings_email_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Email Test */
        post: operations["send_email_test_api_settings_email_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/frameio/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Frameio */
        post: operations["ingest_frameio_api_webhooks_frameio__rule_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhook-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_webhook_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_sync_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_sync_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_sync_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_sync_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_sync_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/sync-rules/{rule_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Rule */
        post: operations["run_rule_api_sync_rules__rule_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync-rules/{rule_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_sync_rules__rule_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync-rules/{rule_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stats */
        get: operations["job_stats_api_sync_rules__rule_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChunkOut */
        ChunkOut: {
            /** Part */
            part: number;
            /** Size */
            size: number;
            /** Url */
            url: string;
        };
        /** CompleteFileResult */
        CompleteFileResult: {
            /** Complete */
            complete: boolean;
            /** Failed */
            failed: boolean;
        };
        /** CompleteSessionRequest */
        CompleteSessionRequest: {
            /** Total Bytes */
            total_bytes?: number | null;
        };
        /** ConnectionStatus */
        ConnectionStatus: {
            /** Connected */
            connected: boolean;
            /** Adobe Email */
            adobe_email?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Needs Refresh */
            needs_refresh?: boolean | null;
            /** Scopes */
            scopes?: string | null;
        };
        /** DestinationCreate */
        DestinationCreate: {
            /** Display Name */
            display_name: string;
            config: components["schemas"]["FrameioConfigIn"];
            /** Logo Url */
            logo_url?: string | null;
            /** Accent Color */
            accent_color?: string | null;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** DestinationOut */
        DestinationOut: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Logo Url */
            logo_url: string | null;
            /** Accent Color */
            accent_color: string | null;
            /** Subtitle */
            subtitle: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DestinationUpdate */
        DestinationUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Accent Color */
            accent_color?: string | null;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** DownloadLinkCreate */
        DownloadLinkCreate: {
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Expires At */
            expires_at?: string | null;
            /** Password */
            password?: string | null;
            /** Max Downloads */
            max_downloads?: number | null;
            /**
             * @default {
             *       "name": false,
             *       "email": false
             *     }
             */
            viewer_fields_required: components["schemas"]["ViewerFields"];
            /**
             * Verify Email
             * @default false
             */
            verify_email: boolean;
            /**
             * Allow Preview
             * @default true
             */
            allow_preview: boolean;
            /** Brand Logo Url */
            brand_logo_url?: string | null;
            /** Brand Accent Color */
            brand_accent_color?: string | null;
            /** Brand Display Name */
            brand_display_name?: string | null;
            /** Brand Subtitle */
            brand_subtitle?: string | null;
        };
        /** DownloadLinkOut */
        DownloadLinkOut: {
            /** Id */
            id: string;
            /** Token */
            token: string;
            /** Public Url */
            public_url: string;
            /** State */
            state: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Expires At */
            expires_at: string | null;
            /** Password Protected */
            password_protected: boolean;
            /** Max Downloads */
            max_downloads: number | null;
            /** Downloads Count */
            downloads_count: number;
            /** Viewer Fields Required */
            viewer_fields_required: {
                [key: string]: boolean;
            };
            /** Verify Email */
            verify_email: boolean;
            /** Allow Preview */
            allow_preview: boolean;
            /** Brand Logo Url */
            brand_logo_url: string | null;
            /** Brand Accent Color */
            brand_accent_color: string | null;
            /** Brand Display Name */
            brand_display_name: string | null;
            /** Brand Subtitle */
            brand_subtitle: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** DownloadLinkUpdate */
        DownloadLinkUpdate: {
            /** Expires At */
            expires_at?: string | null;
            /** Password */
            password?: string | null;
            /** Max Downloads */
            max_downloads?: number | null;
            viewer_fields_required?: components["schemas"]["ViewerFields"] | null;
            /** Verify Email */
            verify_email?: boolean | null;
            /** Allow Preview */
            allow_preview?: boolean | null;
            /** Brand Logo Url */
            brand_logo_url?: string | null;
            /** Brand Accent Color */
            brand_accent_color?: string | null;
            /** Brand Display Name */
            brand_display_name?: string | null;
            /** Brand Subtitle */
            brand_subtitle?: string | null;
        };
        /** DownloadPageOut */
        DownloadPageOut: {
            /** State */
            state: string;
            /** Display Name */
            display_name: string;
            /** Subtitle */
            subtitle: string | null;
            /** Logo Url */
            logo_url: string | null;
            /** Accent Color */
            accent_color: string | null;
            /** Password Required */
            password_required: boolean;
            /** Viewer Fields Required */
            viewer_fields_required: {
                [key: string]: boolean;
            };
            /** Verify Email */
            verify_email: boolean;
            /** Allow Preview */
            allow_preview: boolean;
        };
        /** DownloadUrlResult */
        DownloadUrlResult: {
            /** Url */
            url: string;
        };
        /** EmailStatus */
        EmailStatus: {
            /** Configured */
            configured: boolean;
            /** Smtp Host */
            smtp_host: string | null;
            /** Smtp From */
            smtp_from: string | null;
            /** Notify Email */
            notify_email: string;
        };
        /** FileItemOut */
        FileItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** File Size */
            file_size?: number | null;
            /** Media Type */
            media_type?: string | null;
        };
        /** FileOut */
        FileOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Size */
            size: number | null;
            /** Media Type */
            media_type: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /** FileRequest */
        FileRequest: {
            /** Path */
            path: string;
            /** Size */
            size: number;
        };
        /** FileResult */
        FileResult: {
            /** File Id */
            file_id: string;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Headers */
            headers: {
                [key: string]: string;
            };
        };
        /** FrameioConfigIn */
        FrameioConfigIn: {
            /**
             * Type
             * @default frameio
             * @constant
             */
            type: "frameio";
            /** Account Id */
            account_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Project Id */
            project_id: string;
            /** Folder Id */
            folder_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStats */
        JobStats: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PasswordVerifyRequest */
        PasswordVerifyRequest: {
            /** Password */
            password: string;
        };
        /** PasswordVerifyResult */
        PasswordVerifyResult: {
            /** Ok */
            ok: boolean;
        };
        /** PickerItemOut */
        PickerItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProjectItemOut */
        ProjectItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Root Folder Id */
            root_folder_id?: string | null;
        };
        /** PublicLinkOut */
        PublicLinkOut: {
            /** State */
            state: string;
            /** Display Name */
            display_name: string;
            /** Subtitle */
            subtitle: string | null;
            /** Logo Url */
            logo_url: string | null;
            /** Accent Color */
            accent_color: string | null;
            /** Password Required */
            password_required: boolean;
            /** Max File Size */
            max_file_size: number | null;
            /** Allowed Extensions */
            allowed_extensions: string[] | null;
            /** Uploader Fields Required */
            uploader_fields_required: {
                [key: string]: boolean;
            };
            /** Verify Email */
            verify_email: boolean;
        };
        /** RequestCodeRequest */
        RequestCodeRequest: {
            /** Email */
            email: string;
        };
        /** RequestCodeResult */
        RequestCodeResult: {
            /** Trusted */
            trusted: boolean;
            /** Sent */
            sent: boolean;
        };
        /** SyncJobOut */
        SyncJobOut: {
            /** Id */
            id: string;
            /** Frameio File Id */
            frameio_file_id: string;
            /** Status */
            status: string;
            /** Bytes */
            bytes: number | null;
            /** Sha256 */
            sha256: string | null;
            /** Error */
            error: string | null;
            /** Retry Count */
            retry_count: number;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** SyncRuleCreate */
        SyncRuleCreate: {
            /** Name */
            name: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Destination Path */
            destination_path: string;
            /**
             * Conflict Policy
             * @default rename_suffix
             */
            conflict_policy: string;
            /** Path Template */
            path_template?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** SyncRuleOut */
        SyncRuleOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Destination Path */
            destination_path: string;
            /** Conflict Policy */
            conflict_policy: string;
            /** Path Template */
            path_template: string | null;
            /** Enabled */
            enabled: boolean;
            /** Subscription Active */
            subscription_active: boolean;
            /** Created At */
            created_at: string;
        };
        /** SyncRuleUpdate */
        SyncRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Destination Path */
            destination_path?: string | null;
            /** Conflict Policy */
            conflict_policy?: string | null;
            /** Path Template */
            path_template?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** UploadLinkCreate */
        UploadLinkCreate: {
            /**
             * Destination Id
             * Format: uuid
             */
            destination_id: string;
            /** Expires At */
            expires_at?: string | null;
            /** Password */
            password?: string | null;
            /** Max File Size */
            max_file_size?: number | null;
            /** Allowed Extensions */
            allowed_extensions?: string[] | null;
            /**
             * @default {
             *       "name": false,
             *       "email": false,
             *       "message": false
             *     }
             */
            uploader_fields_required: components["schemas"]["UploaderFields"];
            /**
             * Verify Email
             * @default false
             */
            verify_email: boolean;
            /** Brand Logo Url */
            brand_logo_url?: string | null;
            /** Brand Accent Color */
            brand_accent_color?: string | null;
            /** Brand Display Name */
            brand_display_name?: string | null;
            /** Brand Subtitle */
            brand_subtitle?: string | null;
        };
        /** UploadLinkOut */
        UploadLinkOut: {
            /** Id */
            id: string;
            /** Token */
            token: string;
            /** Public Url */
            public_url: string;
            /** State */
            state: string;
            /** Destination Id */
            destination_id: string;
            /** Destination Name */
            destination_name: string;
            /** Expires At */
            expires_at: string | null;
            /** Password Protected */
            password_protected: boolean;
            /** Max File Size */
            max_file_size: number | null;
            /** Allowed Extensions */
            allowed_extensions: string[] | null;
            /** Uploader Fields Required */
            uploader_fields_required: {
                [key: string]: boolean;
            };
            /** Verify Email */
            verify_email: boolean;
            /** Brand Logo Url */
            brand_logo_url: string | null;
            /** Brand Accent Color */
            brand_accent_color: string | null;
            /** Brand Display Name */
            brand_display_name: string | null;
            /** Brand Subtitle */
            brand_subtitle: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** UploadLinkUpdate */
        UploadLinkUpdate: {
            /** Expires At */
            expires_at?: string | null;
            /** Password */
            password?: string | null;
            /** Max File Size */
            max_file_size?: number | null;
            /** Allowed Extensions */
            allowed_extensions?: string[] | null;
            uploader_fields_required?: components["schemas"]["UploaderFields"] | null;
            /** Verify Email */
            verify_email?: boolean | null;
            /** Brand Logo Url */
            brand_logo_url?: string | null;
            /** Brand Accent Color */
            brand_accent_color?: string | null;
            /** Brand Display Name */
            brand_display_name?: string | null;
            /** Brand Subtitle */
            brand_subtitle?: string | null;
        };
        /** UploaderFields */
        UploaderFields: {
            /**
             * Name
             * @default false
             */
            name: boolean;
            /**
             * Email
             * @default false
             */
            email: boolean;
            /**
             * Message
             * @default false
             */
            message: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewerFields */
        ViewerFields: {
            /**
             * Name
             * @default false
             */
            name: boolean;
            /**
             * Email
             * @default false
             */
            email: boolean;
        };
        /** WebhookEventOut */
        WebhookEventOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Event Type */
            event_type: string | null;
            /** Signature Valid */
            signature_valid: boolean | null;
            /** Processed */
            processed: boolean;
            /** Processed At */
            processed_at: string | null;
            /** Error */
            error: string | null;
            /** Received At */
            received_at: string;
        };
        /** StartSessionRequest */
        portal__routes__public__StartSessionRequest: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Message */
            message?: string | null;
            /** Password */
            password?: string | null;
            /** Code */
            code?: string | null;
        };
        /** StartSessionResult */
        portal__routes__public__StartSessionResult: {
            /** Session Id */
            session_id: string;
        };
        /** StartSessionRequest */
        portal__routes__public_downloads__StartSessionRequest: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            /** Code */
            code?: string | null;
        };
        /** StartSessionResult */
        portal__routes__public_downloads__StartSessionResult: {
            /** Session Id */
            session_id: string;
            /** Files */
            files: components["schemas"]["FileOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    connect_api_frameio_oauth_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_frameio_oauth_callback_get: {
        parameters: {
            query?: {
                state?: string | null;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_frameio_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
        };
    };
    disconnect_api_frameio_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_accounts_api_frameio_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickerItemOut"][];
                };
            };
        };
    };
    list_workspaces_api_frameio_workspaces_get: {
        parameters: {
            query: {
                account_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickerItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_frameio_projects_get: {
        parameters: {
            query: {
                account_id: string;
                workspace_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_api_frameio_folders_get: {
        parameters: {
            query: {
                account_id: string;
                folder_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickerItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_frameio_files_get: {
        parameters: {
            query: {
                account_id: string;
                folder_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_destinations_api_destinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"][];
                };
            };
        };
    };
    create_destination_api_destinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destination_api_destinations__dest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_destination_api_destinations__dest_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_destination_api_destinations__dest_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dest_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_preset_api_upload_links_extension_preset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_links_api_upload_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadLinkOut"][];
                };
            };
        };
    };
    create_link_api_upload_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_api_upload_links__link_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_api_upload_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_link_api_upload_links__link_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadLinkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_link_api_upload_links__link_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_link_api_public_links__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_code_api_public_links__token__request_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_link_password_api_public_links__token__verify_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_public_links__token__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["portal__routes__public__StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["portal__routes__public__StartSessionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_file_upload_api_public_links__token__sessions__session_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_file_api_public_links__token__sessions__session_id__files__file_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                session_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteFileResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_public_links__token__sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_links_api_download_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLinkOut"][];
                };
            };
        };
    };
    create_link_api_download_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_api_download_links__link_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_api_download_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_link_api_download_links__link_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadLinkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_link_api_download_links__link_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_link_api_public_downloads__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_code_api_public_downloads__token__request_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_public_downloads__token__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["portal__routes__public_downloads__StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["portal__routes__public_downloads__StartSessionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_download_url_api_public_downloads__token__sessions__session_id__files__file_id__url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                session_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_status_api_settings_email_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailStatus"];
                };
            };
        };
    };
    send_email_test_api_settings_email_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ingest_frameio_api_webhooks_frameio__rule_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_webhook_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_sync_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRuleOut"][];
                };
            };
        };
    };
    create_rule_api_sync_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_sync_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_sync_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_sync_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_rule_api_sync_rules__rule_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_sync_rules__rule_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stats_api_sync_rules__rule_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
