"""download links

Revision ID: 7d921028445a
Revises: 131190297565
Create Date: 2026-06-09 09:39:44.790336

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d921028445a'
down_revision: str | None = '131190297565'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('viewer_fields_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_preview', sa.Boolean(), nullable=False),
    sa.Column('brand_logo_url', sa.Text(), nullable=True),
    sa.Column('brand_accent_color', sa.String(length=32), nullable=True),
    sa.Column('brand_display_name', sa.String(length=255), nullable=True),
    sa.Column('brand_subtitle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_links_token'), 'download_links', ['token'], unique=True)
    op.create_table('download_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('download_link_id', sa.UUID(), nullable=False),
    sa.Column('viewer_name', sa.String(length=255), nullable=True),
    sa.Column('viewer_email', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['download_link_id'], ['download_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_sessions_download_link_id'), 'download_sessions', ['download_link_id'], unique=False)
    op.create_table('download_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('download_session_id', sa.UUID(), nullable=False),
    sa.Column('frameio_file_id', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('bytes_served', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['download_session_id'], ['download_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_events_download_session_id'), 'download_events', ['download_session_id'], unique=False)
    op.create_index(op.f('ix_download_events_frameio_file_id'), 'download_events', ['frameio_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_events_frameio_file_id'), table_name='download_events')
    op.drop_index(op.f('ix_download_events_download_session_id'), table_name='download_events')
    op.drop_table('download_events')
    op.drop_index(op.f('ix_download_sessions_download_link_id'), table_name='download_sessions')
    op.drop_table('download_sessions')
    op.drop_index(op.f('ix_download_links_token'), table_name='download_links')
    op.drop_table('download_links')
    # ### end Alembic commands ###
